server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    username: jenkinsuzb@gmail.com
    password: xxmnhvbpkqyydnwi
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_cloud
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_db
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create

